server {
    listen 80;
    server_name example.com www.example.com;

    server_tokens on;
    root /var/www/app;

    location / {
        autoindex on;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:3000;
    }
}
